parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony2rest
    database_user:     symfony2
    database_password: 123

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    nelmio_api_doc.formatter.html_formatter.class: Madesst\RestBundle\Formatter\CustomHtmlFormatter